parameters:
#    show_stop_television.example.class: ShowStop\TelevisionBundle\Example

services:
#    show_stop_television.example:
#        class: %show_stop_television.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
